server:
  port: 8081
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/oauth2?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=5
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PWD:123456}
      driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    org.springframework: DEBUG